<?php

namespace Container8mEK7Mi;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getConsole_ArgumentResolver_MapInputService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'console.argument_resolver.map_input' shared service.
     *
     * @return \Symfony\Component\Console\ArgumentResolver\ValueResolver\MapInputValueResolver
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/ArgumentResolver/ValueResolver/ValueResolverInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/ArgumentResolver/ValueResolver/MapInputValueResolver.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/ArgumentResolver/ValueResolver/BuiltinTypeValueResolver.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/ArgumentResolver/ValueResolver/BackedEnumValueResolver.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/ArgumentResolver/ValueResolver/DateTimeValueResolver.php';

        return $container->privates['console.argument_resolver.map_input'] = new \Symfony\Component\Console\ArgumentResolver\ValueResolver\MapInputValueResolver(($container->privates['console.argument_resolver.builtin_type'] ??= new \Symfony\Component\Console\ArgumentResolver\ValueResolver\BuiltinTypeValueResolver()), ($container->privates['console.argument_resolver.backed_enum'] ??= new \Symfony\Component\Console\ArgumentResolver\ValueResolver\BackedEnumValueResolver()), ($container->privates['console.argument_resolver.datetime'] ??= new \Symfony\Component\Console\ArgumentResolver\ValueResolver\DateTimeValueResolver(NULL)), NULL);
    }
}
