<?php

namespace Container8mEK7Mi;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getConsole_ArgumentResolver_BuiltinTypeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'console.argument_resolver.builtin_type' shared service.
     *
     * @return \Symfony\Component\Console\ArgumentResolver\ValueResolver\BuiltinTypeValueResolver
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/ArgumentResolver/ValueResolver/ValueResolverInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/ArgumentResolver/ValueResolver/BuiltinTypeValueResolver.php';

        return $container->privates['console.argument_resolver.builtin_type'] = new \Symfony\Component\Console\ArgumentResolver\ValueResolver\BuiltinTypeValueResolver();
    }
}
