<?php

namespace Container8mEK7Mi;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getConsole_ArgumentResolverService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'console.argument_resolver' shared service.
     *
     * @return \Symfony\Component\Console\ArgumentResolver\ArgumentResolver
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/ArgumentResolver/ArgumentResolverInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/ArgumentResolver/ArgumentResolver.php';

        return $container->services['console.argument_resolver'] = new \Symfony\Component\Console\ArgumentResolver\ArgumentResolver(new RewindableGenerator(function () use ($container) {
            yield 0 => ($container->privates['console.argument_resolver.backed_enum'] ??= new \Symfony\Component\Console\ArgumentResolver\ValueResolver\BackedEnumValueResolver());
            yield 1 => ($container->privates['console.argument_resolver.uid'] ??= new \Symfony\Component\Console\ArgumentResolver\ValueResolver\UidValueResolver());
            yield 2 => ($container->privates['console.argument_resolver.input_file'] ??= new \Symfony\Component\Console\ArgumentResolver\ValueResolver\InputFileValueResolver());
            yield 3 => ($container->privates['console.argument_resolver.builtin_type'] ??= new \Symfony\Component\Console\ArgumentResolver\ValueResolver\BuiltinTypeValueResolver());
            yield 4 => ($container->privates['console.argument_resolver.datetime'] ??= new \Symfony\Component\Console\ArgumentResolver\ValueResolver\DateTimeValueResolver(NULL));
            yield 5 => ($container->privates['console.argument_resolver.map_input'] ?? $container->load('getConsole_ArgumentResolver_MapInputService'));
            yield 6 => ($container->privates['console.argument_resolver.service'] ?? $container->load('getConsole_ArgumentResolver_ServiceService'));
            yield 7 => ($container->privates['console.argument_resolver.default'] ??= new \Symfony\Component\Console\ArgumentResolver\ValueResolver\DefaultValueResolver());
            yield 8 => ($container->privates['console.argument_resolver.variadic'] ??= new \Symfony\Component\Console\ArgumentResolver\ValueResolver\VariadicValueResolver());
        }, 9), new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'Symfony\\Component\\Console\\ArgumentResolver\\ValueResolver\\BackedEnumValueResolver' => ['privates', 'console.argument_resolver.backed_enum', 'getConsole_ArgumentResolver_BackedEnumService', true],
            'Symfony\\Component\\Console\\ArgumentResolver\\ValueResolver\\UidValueResolver' => ['privates', 'console.argument_resolver.uid', 'getConsole_ArgumentResolver_UidService', true],
            'Symfony\\Component\\Console\\ArgumentResolver\\ValueResolver\\InputFileValueResolver' => ['privates', 'console.argument_resolver.input_file', 'getConsole_ArgumentResolver_InputFileService', true],
            'Symfony\\Component\\Console\\ArgumentResolver\\ValueResolver\\BuiltinTypeValueResolver' => ['privates', 'console.argument_resolver.builtin_type', 'getConsole_ArgumentResolver_BuiltinTypeService', true],
            'Symfony\\Component\\Console\\ArgumentResolver\\ValueResolver\\DateTimeValueResolver' => ['privates', 'console.argument_resolver.datetime', 'getConsole_ArgumentResolver_DatetimeService', true],
            'Symfony\\Component\\Console\\ArgumentResolver\\ValueResolver\\MapInputValueResolver' => ['privates', 'console.argument_resolver.map_input', 'getConsole_ArgumentResolver_MapInputService', true],
            'Symfony\\Component\\Console\\ArgumentResolver\\ValueResolver\\ServiceValueResolver' => ['privates', 'console.argument_resolver.service', 'getConsole_ArgumentResolver_ServiceService', true],
            'Symfony\\Component\\Console\\ArgumentResolver\\ValueResolver\\DefaultValueResolver' => ['privates', 'console.argument_resolver.default', 'getConsole_ArgumentResolver_DefaultService', true],
            'Symfony\\Component\\Console\\ArgumentResolver\\ValueResolver\\VariadicValueResolver' => ['privates', 'console.argument_resolver.variadic', 'getConsole_ArgumentResolver_VariadicService', true],
        ], [
            'Symfony\\Component\\Console\\ArgumentResolver\\ValueResolver\\BackedEnumValueResolver' => 'Symfony\\Component\\Console\\ArgumentResolver\\ValueResolver\\BackedEnumValueResolver',
            'Symfony\\Component\\Console\\ArgumentResolver\\ValueResolver\\UidValueResolver' => 'Symfony\\Component\\Console\\ArgumentResolver\\ValueResolver\\UidValueResolver',
            'Symfony\\Component\\Console\\ArgumentResolver\\ValueResolver\\InputFileValueResolver' => 'Symfony\\Component\\Console\\ArgumentResolver\\ValueResolver\\InputFileValueResolver',
            'Symfony\\Component\\Console\\ArgumentResolver\\ValueResolver\\BuiltinTypeValueResolver' => 'Symfony\\Component\\Console\\ArgumentResolver\\ValueResolver\\BuiltinTypeValueResolver',
            'Symfony\\Component\\Console\\ArgumentResolver\\ValueResolver\\DateTimeValueResolver' => 'Symfony\\Component\\Console\\ArgumentResolver\\ValueResolver\\DateTimeValueResolver',
            'Symfony\\Component\\Console\\ArgumentResolver\\ValueResolver\\MapInputValueResolver' => 'Symfony\\Component\\Console\\ArgumentResolver\\ValueResolver\\MapInputValueResolver',
            'Symfony\\Component\\Console\\ArgumentResolver\\ValueResolver\\ServiceValueResolver' => 'Symfony\\Component\\Console\\ArgumentResolver\\ValueResolver\\ServiceValueResolver',
            'Symfony\\Component\\Console\\ArgumentResolver\\ValueResolver\\DefaultValueResolver' => 'Symfony\\Component\\Console\\ArgumentResolver\\ValueResolver\\DefaultValueResolver',
            'Symfony\\Component\\Console\\ArgumentResolver\\ValueResolver\\VariadicValueResolver' => 'Symfony\\Component\\Console\\ArgumentResolver\\ValueResolver\\VariadicValueResolver',
        ]));
    }
}
