<?php

namespace Container8mEK7Mi;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getServicesResetterService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'services_resetter' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServicesResetter
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/dependency-injection/ServicesResetterInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/dependency-injection/ServicesResetter.php';

        return $container->services['services_resetter'] = new \Symfony\Component\DependencyInjection\ServicesResetter(new RewindableGenerator(function () use ($container) {
            if (isset($container->privates['container.env_var_processor'])) {
                yield 'container.env_var_processor' => ($container->privates['container.env_var_processor'] ?? null);
            }
            if (isset($container->privates['controller.cache_attribute_listener'])) {
                yield 'controller.cache_attribute_listener' => ($container->privates['controller.cache_attribute_listener'] ?? null);
            }
            if (false) {
                yield 'cache.controller_expression_language' => null;
            }
            if (isset($container->services['request_stack'])) {
                yield 'request_stack' => ($container->services['request_stack'] ?? null);
            }
            if (isset($container->services['cache.app'])) {
                yield 'cache.app' => ($container->services['cache.app'] ?? null);
            }
            if (isset($container->services['cache.system'])) {
                yield 'cache.system' => ($container->services['cache.system'] ?? null);
            }
            if (false) {
                yield 'cache.validator' => null;
            }
            if (false) {
                yield 'cache.serializer' => null;
            }
            if (false) {
                yield 'cache.property_info' => null;
            }
            if (isset($container->privates['session_listener'])) {
                yield 'session_listener' => ($container->privates['session_listener'] ?? null);
            }
        }, fn () => 0 + (int) (isset($container->privates['container.env_var_processor'])) + (int) (isset($container->privates['controller.cache_attribute_listener'])) + (int) (false) + (int) (isset($container->services['request_stack'])) + (int) (isset($container->services['cache.app'])) + (int) (isset($container->services['cache.system'])) + (int) (false) + (int) (false) + (int) (false) + (int) (isset($container->privates['session_listener']))), ['container.env_var_processor' => ['reset'], 'controller.cache_attribute_listener' => ['?reset'], 'cache.controller_expression_language' => ['reset'], 'request_stack' => ['?resetRequestFormats'], 'cache.app' => ['reset'], 'cache.system' => ['reset'], 'cache.validator' => ['reset'], 'cache.serializer' => ['reset'], 'cache.property_info' => ['reset'], 'session_listener' => ['reset']]);
    }
}
