framework:
    secret: '%env(APP_SECRET)%'

    session: true

    validation: ~

when@test:
    framework:
        test: true
        session:
            storage_factory_id: session.storage.factory.mock_file

        validation:
            not_compromised_password: false