services:

  ### DATABASE ###
  database:
    image: postgres:16-alpine
    container_name: symfony_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: app
      POSTGRES_USER: app
      POSTGRES_PASSWORD: "!ChangeMe!"
    ports:
      - "5432:5432"
    volumes:
      - database_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U app -d app"]
      interval: 5s
      timeout: 5s
      retries: 10

  ### APP (SYMFONY) ###
  app:
    build: .
    container_name: symfony_app
    restart: unless-stopped
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      database:
        condition: service_healthy
    environment:
      DATABASE_URL: "postgresql://app:!ChangeMe!@database:5432/app?serverVersion=16&charset=utf8"
    command: >
      sh -c "
      php bin/console doctrine:database:create --if-not-exists --no-interaction &&
      php bin/console doctrine:migrations:migrate --no-interaction &&
      php -S 0.0.0.0:8000 -t public
      "

volumes:
  database_data: