<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerM02LMIG\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerM02LMIG/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerM02LMIG.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerM02LMIG\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerM02LMIG\App_KernelDevDebugContainer([
    'container.build_hash' => 'M02LMIG',
    'container.build_id' => '75368d1b',
    'container.build_time' => 1782485091,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerM02LMIG');
